jQuery(function(){
  jQuery('#busca_rapida')
  .focus(function(){
   if(jQuery(this).val()=='Busca Rápida')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Busca Rápida');
   }
  });
 })
 
 jQuery(function(){
  jQuery('#nome-contato')
  .focus(function(){
   if(jQuery(this).val()=='Nome:')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Nome:');
   }
  });
 })
 
 jQuery(function(){
  jQuery('#ddd-contato')
  .focus(function(){
   if(jQuery(this).val()=='DDD:')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('DDD:');
   }
  });
 })
 
 jQuery(function(){
  jQuery('#tel-contato')
  .focus(function(){
   if(jQuery(this).val()=='Telefone:')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Telefone:');
   }
  });
 })
 
jQuery(function(){
  jQuery('#email-contato')
  .focus(function(){
   if(jQuery(this).val()=='E-mail:')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('E-mail:');
   }
  });
 })
 jQuery(function(){
  jQuery('#cidade-contato')
  .focus(function(){
   if(jQuery(this).val()=='Cidade:')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Cidade:');
   }
  });
 })
  jQuery(function(){
  jQuery('#mensagem-contato')
  .focus(function(){
   if(jQuery(this).val()=='Mensagem:')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Mensagem:');
   }
  });
 })
   jQuery(function(){
  jQuery('#usuario')
  .focus(function(){
   if(jQuery(this).val()=='Usuário')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Usuário');
   }
  });
 })
   jQuery(function(){
  jQuery('#senha')
  .focus(function(){
   if(jQuery(this).val()=='Senha')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Senha');
   }
  });
 })
   jQuery(function(){
  jQuery('#usuario_rv')
  .focus(function(){
   if(jQuery(this).val()=='Usuário')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Usuário');
   }
  });
 })
   jQuery(function(){
  jQuery('#senha_rv')
  .focus(function(){
   if(jQuery(this).val()=='Senha')
   {
    jQuery(this).val('');
   }
  })
  .blur(function(){
   if(jQuery(this).val()=='')
   {
    jQuery(this).val('Senha');
   }
  });
 })
 